/*
 * generated by Xtext
 */
package co.edu.javeriana.isml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import co.edu.javeriana.isml.ui.internal.IsmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IsmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IsmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IsmlActivator.getInstance().getInjector(IsmlActivator.CO_EDU_JAVERIANA_ISML_ISML);
	}
	
}
