/*
 * generated by Xtext
 */
package co.edu.javeriana.isml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import co.edu.javeriana.isml.services.IsmlGrammarAccess;

public class IsmlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IsmlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected co.edu.javeriana.isml.parser.antlr.internal.InternalIsmlParser createParser(XtextTokenStream stream) {
		return new co.edu.javeriana.isml.parser.antlr.internal.InternalIsmlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "InformationSystem";
	}
	
	public IsmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IsmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
