/*
 * generated by Xtext
 */
package co.edu.javeriana.isml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IsmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return co.edu.javeriana.isml.ui.internal.IsmlActivator.getInstance().getInjector("co.edu.javeriana.isml.Isml");
	}

}
